Add scanner input file and `dataFile.txt`
mangkoran/oop-project pull request #9
Opened 2021-07-05 17:57 UTC by leonnahart

I added an empty constructor to Movie class, dataFile.txt for input file, and input file scanner. Please check the code, thank you.

2021-07-06 03:57 UTC, mangkoran requested changes
I leave some comments. Please review all the comments

2021-07-06 03:57 UTC, mangkoran commented on src/TheaterTicketSystem.java
> +                Movie tempMovie = new Movie();
Could you make it so we don't need empty constructor?  `tempMovie` can be moved to line 51 right before we add `tempMovie` into `tempMovies`
```suggestion
```

2021-07-06 03:57 UTC, mangkoran commented on src/TheaterTicketSystem.java
> +
Move `tempMovie` declaration here. My suggestion is just an outline, change accordingly
```suggestion
                Movie tempMovie = new Movie(tempTitle, tempRunningTime, ...);
```

2021-07-06 03:57 UTC, mangkoran commented on src/TheaterTicketSystem.java
> +                tempMovie.setTitle(data.next()); //set movie title
```suggestion
                String tempTitle = data.next();
```

2021-07-06 03:57 UTC, mangkoran commented on src/TheaterTicketSystem.java
> +                tempMovie.setRunningTime(data.nextInt());//set movie running time
```suggestion
                int tempRunningTime = data.nextInt();
```

2021-07-06 03:57 UTC, mangkoran commented on src/TheaterTicketSystem.java
> +                tempMovie.setAgeRating(tempAgeRating);
```suggestion
```

2021-07-06 03:57 UTC, mangkoran commented on src/TheaterTicketSystem.java
> +                tempMovie.setReleaseDate(testCal);//set to movie()
```suggestion
```

2021-07-06 03:57 UTC, mangkoran commented on src/TheaterTicketSystem.java
> +                tempMovie.setTicketPrice(tempTicketPrice);//set the prices to movie()
```suggestion
```

2021-07-06 03:57 UTC, mangkoran commented on src/TheaterTicketSystem.java
> +                tempMovie.setTimeSeats(testTimeSeats);
```suggestion
```

2021-07-06 03:57 UTC, mangkoran commented on src/movie/Movie.java
> +
We need to avoid the usage of empty constructor to prevent uninitialized object. By only using parameterized constructor we will know that all `Movie` object created in our program will always have value in their fields
```suggestion
```

2021-07-06 03:57 UTC, mangkoran commented on src/TheaterTicketSystem.java
> +                testTimeSeats.add(new TimeSeat(data.next(), testCal, testSeats));
These lines is fine IF each movie only have 1 element in `timeSeats`. Please update it so that we can insert multiple elements in `timeSeats`

2021-07-06 03:59 UTC, mangkoran commented
Also please do not use the "Commit suggestion" button in GitHub, as my suggestions mostly just outline and I didn't check their error in IDE
![image](https://user-images.githubusercontent.com/57625126/124540270-a1035700-de51-11eb-8201-f5464e876dfe.png)

2021-07-06 04:01 UTC, mangkoran commented
I convert this to draft PR for now

2021-07-06 08:28 UTC, leonnahart commented
I have changed the related code for input file Scanner and deleted the empty constructor for `Moive` class.
Please check the code again, thank you.

2021-07-06 09:30 UTC, mangkoran requested changes
How if we want to input multiple time seats?

2021-07-06 09:32 UTC, mangkoran commented on src/TheaterTicketSystem.java
> +                testTimeSeats.add(new TimeSeat(data.next(), testCal, testSeats));
Take a look at these lines. Currently it only support 1 time seat per movie input from input file. Make it so we can input multiple time seats per movie

2021-07-06 14:02 UTC, leonnahart commented
Could you please check the latest code? I tried your suggestion (from the latest meeting) there is some error occur.

2021-07-06 14:03 UTC, mangkoran commented
Then try to solve that error. My suggestion is just an outline

2021-07-07 12:31 UTC, mangkoran commented
Already done with https://github.com/mangkoran/oop-project/pull/13

2021-07-07 12:31 UTC, closed without merging